package webservice;


import org.springframework.stereotype.Component;
import org.springframework.util.Assert;
import webservice.autogeneratedXml.SendMT;

import javax.annotation.PostConstruct;
import java.util.HashMap;
import java.util.Map;

@Component
public class RequestRepository {
    private static final Map <String, SendMT> sendMTMap = new HashMap<>();


    @PostConstruct
    public void initData() {
            SendMT mt = new SendMT();
            mt.setPhoneNum("0984898981");
            mt.setSmsMsg("quae divum incedo");
            mt.setRequestor("new_iib");
            mt.setRequesPassword("IIB@Vpbank");
            mt.setRequestBranch("VN0010001");
            mt.setAcNum("11");

            sendMTMap.put(mt.getClass().getName(), mt);
    }
    public SendMT sendMsg(String name) {
        Assert.notNull(name, "The country's name must not be null");
        return sendMTMap.get(name);
    }
}
