package webservice;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ws.server.endpoint.annotation.PayloadRoot;
import org.springframework.ws.server.endpoint.annotation.RequestPayload;
import org.springframework.ws.server.endpoint.annotation.ResponsePayload;
import org.springframework.ws.server.endpoint.annotation.Endpoint;
import webservice.autogeneratedXml.ObjectFactory;
import webservice.autogeneratedXml.SendMT;
import webservice.autogeneratedXml.SendMTResponse;


@Endpoint
public class StubEndpoint {
    private static final String NAMESPACE_URI = "http://tempuri.org/";
    private RequestRepository requestRepository;

    @Autowired
    public StubEndpoint(RequestRepository requestRepository){
        this.requestRepository = requestRepository;
    }


    @PayloadRoot(namespace = NAMESPACE_URI, localPart = "SendMT")
    @ResponsePayload
    public SendMTResponse sendMTRequest(@RequestPayload RequestRepository  mt) {

        SendMTResponse response = new SendMTResponse();

        response.setSendMTResult(0);


        return response;
    }
}
