package webservice;


import org.springframework.ws.server.endpoint.annotation.PayloadRoot;
import org.springframework.ws.server.endpoint.annotation.RequestPayload;
import org.springframework.ws.server.endpoint.annotation.ResponsePayload;
import org.springframework.ws.server.endpoint.annotation.Endpoint;
import webservice.autogeneratedXml.ObjectFactory;
import webservice.autogeneratedXml.SendMT;
import webservice.autogeneratedXml.SendMTResponse;


@Endpoint
public class StubEndpoint {
    @PayloadRoot(namespace = "http://in28minutes.com/students", localPart = "SendMT")
    @ResponsePayload
    public SendMTResponse sendMTResponse(@RequestPayload SendMT  mt) {
        SendMTResponse response = new SendMTResponse();

        response.setSendMTResult(0);


        return response;
    }
}
