
package webservice.autogeneratedXml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the webservice.autogeneratedXml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: webservice.autogeneratedXml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendMTResponse }
     * 
     */
    public SendMTResponse createSendMTResponse() {
        return new SendMTResponse();
    }

    /**
     * Create an instance of {@link SendMTFullResponse }
     * 
     */
    public SendMTFullResponse createSendMTFullResponse() {
        return new SendMTFullResponse();
    }

    /**
     * Create an instance of {@link SendCustomEmailResponse }
     * 
     */
    public SendCustomEmailResponse createSendCustomEmailResponse() {
        return new SendCustomEmailResponse();
    }

    /**
     * Create an instance of {@link SendMTFull }
     * 
     */
    public SendMTFull createSendMTFull() {
        return new SendMTFull();
    }

    /**
     * Create an instance of {@link SendCustomEmail }
     * 
     */
    public SendCustomEmail createSendCustomEmail() {
        return new SendCustomEmail();
    }

    /**
     * Create an instance of {@link SendMT }
     * 
     */
    public SendMT createSendMT() {
        return new SendMT();
    }

    /**
     * Create an instance of {@link SendSMSQueue }
     * 
     */
    public SendSMSQueue createSendSMSQueue() {
        return new SendSMSQueue();
    }

    /**
     * Create an instance of {@link SendSMSQueueResponse }
     * 
     */
    public SendSMSQueueResponse createSendSMSQueueResponse() {
        return new SendSMSQueueResponse();
    }

}
