
package webservice.autogeneratedXml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SendSMSQueueResult" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * dfg
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendSMSQueueResult"
})
@XmlRootElement(name = "SendSMSQueueResponse")
public class SendSMSQueueResponse {

    @XmlElement(name = "SendSMSQueueResult")
    protected int sendSMSQueueResult;

    /**
     * Gets the value of the sendSMSQueueResult property.
     * 
     */
    public int getSendSMSQueueResult() {
        return sendSMSQueueResult;
    }

    /**
     * Sets the value of the sendSMSQueueResult property.
     * 
     */
    public void setSendSMSQueueResult(int value) {
        this.sendSMSQueueResult = value;
    }

}
