
package webservice.autogeneratedXml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * fe
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SendCustomEmailResult" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendCustomEmailResult"
})
@XmlRootElement(name = "SendCustomEmailResponse")
public class SendCustomEmailResponse {

    @XmlElement(name = "SendCustomEmailResult")
    protected int sendCustomEmailResult;

    /**
     * Gets the value of the sendCustomEmailResult property.
     * 
     */
    public int getSendCustomEmailResult() {
        return sendCustomEmailResult;
    }

    /**
     * Sets the value of the sendCustomEmailResult property.
     * 
     */
    public void setSendCustomEmailResult(int value) {
        this.sendCustomEmailResult = value;
    }

}
