
package webservice.autogeneratedXml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SendMTFullResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendMTFullResult"
})
@XmlRootElement(name = "SendMTFullResponse")
public class SendMTFullResponse {

    @XmlElement(name = "SendMTFullResult")
    protected String sendMTFullResult;

    /**
     * Gets the value of the sendMTFullResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendMTFullResult() {
        return sendMTFullResult;
    }

    /**
     * Sets the value of the sendMTFullResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendMTFullResult(String value) {
        this.sendMTFullResult = value;
    }

}
