
package webservice.autogeneratedXml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="smsqueueID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * dfg
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "smsqueueID"
})
@XmlRootElement(name = "SendSMSQueue")
public class SendSMSQueue {

    protected long smsqueueID;

    /**
     * Gets the value of the smsqueueID property.
     * 
     */
    public long getSmsqueueID() {
        return smsqueueID;
    }

    /**
     * Sets the value of the smsqueueID property.
     * 
     */
    public void setSmsqueueID(long value) {
        this.smsqueueID = value;
    }

}
